In [1]:
import numpy as np
import pandas as pd
import sys

In [2]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [3]:
df.shape

(4, 4)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64
dtypes: float64(3), int64(1)
memory usage: 256.0 bytes

In [5]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [6]:
df.dropna()

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [7]:
df.dropna(axis=1)

   Column D
0         5
1         8
2        34
3       110

In [8]:
 df.dropna(how='all')

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [9]:
df.dropna(thresh=3,axis='columns') #3 values to be filled

   Column B  Column C  Column D
0       2.0       NaN         5
1       8.0       9.0         8
2      31.0      32.0        34
3       NaN     100.0       110

In [10]:
df.fillna(df.mean())

   Column A   Column B  Column C  Column D
0       1.0   2.000000      47.0         5
1      15.5   8.000000       9.0         8
2      30.0  31.000000      32.0        34
3      15.5  13.666667     100.0       110

In [11]:
s=pd.Series([1,2,3,np.nan,4,np.nan,8,np.nan,10])

In [12]:
s.fillna(method='ffill')

0     1.0
1     2.0
2     3.0
3     3.0
4     4.0
5     4.0
6     8.0
7     8.0
8    10.0
dtype: float64

In [13]:
s.fillna(method='bfill')

0     1.0
1     2.0
2     3.0
3     4.0
4     4.0
5     8.0
6     8.0
7    10.0
8    10.0
dtype: float64

In [14]:
s.dropna().count()

6

In [15]:
  df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

In [16]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [17]:
df['Sex'].value_counts()

F    2
D    1
M    1
?    1
Name: Sex, dtype: int64

In [18]:
df['Sex'].replace({'D':'M','?':'F'})

0    M
1    F
2    F
3    M
4    F
Name: Sex, dtype: object

In [19]:
df.replace({
    'Sex':{
        'D':'M',
        '?':'F'
    },
    'Age':{
        290:29
    }
})

  Sex  Age
0   M   29
1   F   30
2   F   24
3   M   29
4   F   25

In [20]:
df[df['Age']>100]

  Sex  Age
3   D  290

In [21]:
df.loc[df['Age']>100,'Age'] = df.loc[df['Age']>100,'Age']/10
df

  Sex   Age
0   M  29.0
1   F  30.0
2   F  24.0
3   D  29.0
4   ?  25.0