In [1]:
import pandas as pd
import numpy as np
import sys

## Note: Chnages made thorough pandas are immutable(Can't reflect)

In [2]:
df = pd.DataFrame({
    'Population': [35.467, 63.951, 80.94 , 60.665, 127.061, 64.511, 318.523],
    'GDP': [
        1785387,
        2833687,
        3874437,
        2167744,
        4602367,
        2950039,
        17348075
    ],
    'Surface Area': [
        9984670,
        640679,
        357114,
        301336,
        377930,
        242495,
        9525067
    ],
    'HDI': [
        0.913,
        0.888,
        0.916,
        0.873,
        0.891,
        0.907,
        0.915
    ],
    'Continent': [
        'America',
        'Europe',
        'Europe',
        'Europe',
        'Asia',
        'Europe',
        'America'
    ]
}, columns=['Population', 'GDP', 'Surface Area', 'HDI', 'Continent'])
df.index = [
    'Canada',
    'France',
    'Germany',
    'Italy',
    'Japan',
    'United Kingdom',
    'United States',
  ]
df.title="Country"

In [3]:
mask=df['Population']>70
mask

Canada            False
France            False
Germany            True
Italy             False
Japan              True
United Kingdom    False
United States      True
Name: Population, dtype: bool

In [4]:
df.loc[mask]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [5]:
df.loc[df['Population']>70,'Population']

Germany           80.940
Japan            127.061
United States    318.523
Name: Population, dtype: float64

In [6]:
df[df['Population']>70]

               Population       GDP  Surface Area    HDI Continent
Germany            80.940   3874437        357114  0.916    Europe
Japan             127.061   4602367        377930  0.891      Asia
United States     318.523  17348075       9525067  0.915   America

In [7]:
df.loc[df['Population']>70,['Population','GDP']]

               Population       GDP
Germany            80.940   3874437
Japan             127.061   4602367
United States     318.523  17348075

In [8]:
df.drop('Canada')

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [9]:
df.drop(['Canada','Japan'])

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Italy               60.665   2167744        301336  0.873    Europe
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [10]:
df.drop(columns=['Population','HDI'])

                     GDP  Surface Area Continent
Canada           1785387       9984670   America
France           2833687        640679    Europe
Germany          3874437        357114    Europe
Italy            2167744        301336    Europe
Japan            4602367        377930      Asia
United Kingdom   2950039        242495    Europe
United States   17348075       9525067   America

In [11]:
df.loc[df['Surface Area']>1000000]

               Population       GDP  Surface Area    HDI Continent
Canada             35.467   1785387       9984670  0.913   America
United States     318.523  17348075       9525067  0.915   America

In [12]:
df.drop(['Italy','Canada'],axis=0)

                Population       GDP  Surface Area    HDI Continent
France              63.951   2833687        640679  0.888    Europe
Germany             80.940   3874437        357114  0.916    Europe
Japan              127.061   4602367        377930  0.891      Asia
United Kingdom      64.511   2950039        242495  0.907    Europe
United States      318.523  17348075       9525067  0.915   America

In [13]:
df[['Population', 'GDP']] / 100
df['Population']*100

Canada             3546.7
France             6395.1
Germany            8094.0
Italy              6066.5
Japan             12706.1
United Kingdom     6451.1
United States     31852.3
Name: Population, dtype: float64

In [14]:
crisis=pd.Series([-1_00_000,-0.3],index=['GDP','HDI'])
crisis

GDP   -100000.0
HDI        -0.3
dtype: float64

In [15]:
df[['GDP','HDI']]

                     GDP    HDI
Canada           1785387  0.913
France           2833687  0.888
Germany          3874437  0.916
Italy            2167744  0.873
Japan            4602367  0.891
United Kingdom   2950039  0.907
United States   17348075  0.915

In [16]:
df[['GDP','HDI']]+crisis

                       GDP    HDI
Canada           1685387.0  0.613
France           2733687.0  0.588
Germany          3774437.0  0.616
Italy            2067744.0  0.573
Japan            4502367.0  0.591
United Kingdom   2850039.0  0.607
United States   17248075.0  0.615

In [17]:
 #modify
 langs=pd.Series(
     ['French','German','Italian'],
     index=['France','Germany','Italy'],
     name='Language'
 )

In [18]:
df['Language']=langs
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America      NaN
France              63.951   2833687        640679  0.888    Europe   French
Germany             80.940   3874437        357114  0.916    Europe   German
Italy               60.665   2167744        301336  0.873    Europe  Italian
Japan              127.061   4602367        377930  0.891      Asia      NaN
United Kingdom      64.511   2950039        242495  0.907    Europe      NaN
United States      318.523  17348075       9525067  0.915   America      NaN

In [19]:
df['Language']='English'
df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English

In [20]:
#rename
df.rename(
    columns={
        'HDI':'Human Development Index',
        'Anual Popcorn Consumption':'APC'
    },index={
        'United States':'USA',
        'United Kingdom':'UK',
        'Argentina':'AR'
    }
)

         Population       GDP  ...  Continent  Language
Canada       35.467   1785387  ...    America   English
France       63.951   2833687  ...     Europe   English
Germany      80.940   3874437  ...     Europe   English
Italy        60.665   2167744  ...     Europe   English
Japan       127.061   4602367  ...       Asia   English
UK           64.511   2950039  ...     Europe   English
USA         318.523  17348075  ...    America   English

[7 rows x 6 columns]

In [21]:
 df

                Population       GDP  Surface Area    HDI Continent Language
Canada              35.467   1785387       9984670  0.913   America  English
France              63.951   2833687        640679  0.888    Europe  English
Germany             80.940   3874437        357114  0.916    Europe  English
Italy               60.665   2167744        301336  0.873    Europe  English
Japan              127.061   4602367        377930  0.891      Asia  English
United Kingdom      64.511   2950039        242495  0.907    Europe  English
United States      318.523  17348075       9525067  0.915   America  English